import React, { useState, useEffect } from 'react';
import useInView from '../hooks/useInView';

const projectData = [
    {
        title: "Flow Detective",
        subtitle: "Real Time Distributed Anomaly Detection Pipeline",
        badge: "Accepted · ICICT London 2026",
        description: "A zero-day anomaly detection system built for real scale. Processes 20,000+ network records in real time through a Kafka pipeline, detects threats using an ensemble of unsupervised models, and hits 88.3% recall with under 300ms latency. Also trained a W-GAN to generate synthetic attack traffic so the models generalize to unseen threats.",
        tags: ["Apache Kafka", "Python", "Scikit-learn", "Docker", "W-GAN", "Pandas", "NumPy"],
        link: "https://github.com/akshatb29",
        accent: "from-pink-500 to-rose-500",
        glowColor: "rgba(236,72,153,0.18)",
        labelColor: "text-pink-400",
        borderColor: "rgba(236,72,153,0.3)",
    },
    {
        title: "SelfAlign",
        subtitle: "Multi-LLM Collaborative Code Generation System",
        description: "A multi-agent system built on LangGraph where specialized agents plan, generate, test, and fix code collaboratively. Uses Graph-of-Thought prompting for stronger reasoning, sandboxed Docker execution for safe testing, and iterative self-correction loops — so the output actually works, not just compiles.",
        tags: ["LangGraph", "LangChain", "Python", "Docker", "Prompt Engineering", "LLMs"],
        link: "https://github.com/akshatb29",
        accent: "from-violet-500 to-purple-600",
        glowColor: "rgba(139,92,246,0.18)",
        labelColor: "text-violet-400",
        borderColor: "rgba(139,92,246,0.3)",
    },
    {
        title: "CoverAI",
        subtitle: "Full Stack LLM-Powered Cover Letter Generator",
        description: "A full-stack web app that generates personalized, ATS-optimized cover letters from your resume and a job description. Parses PDFs, runs a LangChain and Gemini powered generation pipeline, handles JWT auth, and stores user history in SQL. Built to actually feel good to use.",
        tags: ["React", "FastAPI", "LangChain", "Gemini", "JWT", "SQL", "Vite", "PyMuPDF"],
        link: "https://github.com/akshatb29",
        accent: "from-sky-400 to-blue-500",
        glowColor: "rgba(56,189,248,0.15)",
        labelColor: "text-sky-400",
        borderColor: "rgba(56,189,248,0.3)",
    },
    {
        title: "Zero-Day Attack Detection",
        subtitle: "Reinforcement Learning Based Network Security System",
        description: "An RL-based system that detects and mitigates zero-day network attacks in real time. The model continuously learns evolving attack patterns using synthetic traffic generated by a W-GAN. Used Mininet and a POX controller for realistic network simulation, with Kafka and Logstash powering the streaming pipeline.",
        tags: ["Python", "Reinforcement Learning", "W-GAN", "Apache Kafka", "Mininet", "Logstash"],
        link: "",
        accent: "from-orange-400 to-red-500",
        glowColor: "rgba(251,146,60,0.15)",
        labelColor: "text-orange-400",
        borderColor: "rgba(251,146,60,0.3)",
    },
    {
        title: "Encryption-Decryption via TCP",
        subtitle: "Secure File Transfer over SSL with Custom Encryption",
        description: "A client-server application for secure file transfer over TCP with SSL. Implements XOR-based custom encryption using a shared secret key. The server handles multiple concurrent clients via Python threading and SSL certificates. Clients upload files, receive the encrypted response, and get a real-time decryption preview.",
        tags: ["Python", "TCP Sockets", "SSL", "XOR Encryption", "Threading"],
        link: "https://github.com/akshatb29/ENCRYPTION-DECRYPTION-USING-TCP",
        accent: "from-yellow-400 to-amber-500",
        glowColor: "rgba(250,204,21,0.12)",
        labelColor: "text-yellow-400",
        borderColor: "rgba(250,204,21,0.25)",
    },
    {
        title: "3D Scene Reconstruction",
        subtitle: "Hybrid Neural Network for 3D Scene Reconstruction",
        description: "A deep learning model that reconstructs high-fidelity 3D scenes from sparse 2D images. Combines voxel grids, mesh generation, and Neural Radiance Fields for rich output. Uses the KITTI dataset for depth-aware feature extraction and disparity mapping, with applications in autonomous navigation and AR/VR.",
        tags: ["Python", "NeRF", "Deep Learning", "KITTI", "3D Vision", "PyTorch"],
        link: "",
        accent: "from-indigo-400 to-blue-600",
        glowColor: "rgba(99,102,241,0.15)",
        labelColor: "text-indigo-400",
        borderColor: "rgba(99,102,241,0.3)",
    },
];

/* ── Modal overlay ── */
const ProjectModal = ({ project, onClose }) => {
    const open = project !== null;

    // Close on ESC
    useEffect(() => {
        const onKey = (e) => { if (e.key === 'Escape') onClose(); };
        window.addEventListener('keydown', onKey);
        return () => window.removeEventListener('keydown', onKey);
    }, [onClose]);

    // Lock scroll when open
    useEffect(() => {
        document.body.style.overflow = open ? 'hidden' : '';
        return () => { document.body.style.overflow = ''; };
    }, [open]);

    return (
        /* Backdrop */
        <div
            onClick={onClose}
            className="fixed inset-0 z-50 flex items-center justify-center px-4"
            style={{
                background: 'rgba(0,0,0,0.85)',
                backdropFilter: open ? 'blur(12px)' : 'blur(0px)',
                opacity: open ? 1 : 0,
                pointerEvents: open ? 'auto' : 'none',
                transition: 'opacity 0.35s ease, backdrop-filter 0.35s ease',
            }}
        >
            {/* Panel */}
            <div
                onClick={(e) => e.stopPropagation()}
                className="relative w-full max-w-2xl rounded-3xl overflow-hidden"
                style={{
                    background: 'rgba(8,8,8,0.97)',
                    border: `1px solid ${project?.borderColor ?? 'rgba(255,255,255,0.1)'}`,
                    boxShadow: `0 0 140px 0 ${project?.glowColor ?? 'rgba(255,255,255,0.05)'}, 0 50px 100px rgba(0,0,0,0.7)`,
                    transform: open
                        ? 'scale(1) translateY(0) rotateX(0deg)'
                        : 'scale(0.85) translateY(60px) rotateX(8deg)',
                    transformOrigin: 'center bottom',
                    opacity: open ? 1 : 0,
                    transition: 'transform 0.55s cubic-bezier(0.16,1,0.3,1), opacity 0.4s ease',
                }}
            >
                {/* Top gradient bar */}
                {project && (
                    <div className={`h-1 w-full bg-gradient-to-r ${project.accent}`} />
                )}

                <div className="p-8 md:p-10">
                    {/* Close button */}
                    <button
                        onClick={onClose}
                        className="absolute top-6 right-6 w-8 h-8 rounded-full bg-white/5 border border-white/10
                                   flex items-center justify-center text-gray-500 hover:text-white
                                   hover:bg-white/10 transition-colors duration-200"
                    >
                        <svg viewBox="0 0 24 24" className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M18 6L6 18M6 6l12 12" strokeLinecap="round" />
                        </svg>
                    </button>

                    {/* Badge */}
                    {project?.badge && (
                        <span className={`inline-block text-[11px] font-semibold tracking-widest uppercase px-3 py-1 rounded-full bg-white/5 border border-white/10 mb-5 ${project.labelColor}`}>
                            {project.badge}
                        </span>
                    )}

                    {/* Title */}
                    <h2 className={`text-3xl md:text-5xl font-extrabold bg-gradient-to-r ${project?.accent} bg-clip-text text-transparent leading-tight mb-2`}>
                        {project?.title}
                    </h2>
                    <p className="text-gray-500 text-base mb-6">{project?.subtitle}</p>

                    {/* Description */}
                    <p className="text-gray-300 text-base leading-relaxed mb-8">
                        {project?.description}
                    </p>

                    {/* Tags */}
                    <div className="flex flex-wrap gap-2 mb-8">
                        {project?.tags.map(tag => (
                            <span
                                key={tag}
                                className="text-sm px-3 py-1.5 rounded-full bg-white/[0.04] border border-white/[0.08] text-gray-400"
                            >
                                {tag}
                            </span>
                        ))}
                    </div>

                    {/* GitHub link — hidden if no link */}
                    {project?.link ? (
                        <a
                            href={project.link}
                            target="_blank"
                            rel="noopener noreferrer"
                            className={`inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold
                                        bg-gradient-to-r ${project.accent} text-white
                                        hover:opacity-90 transition-opacity duration-200`}
                        >
                            <svg viewBox="0 0 24 24" className="w-4 h-4" fill="currentColor">
                                <path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" />
                            </svg>
                            View on GitHub
                        </a>
                    ) : (
                        <span className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold border border-white/10 text-gray-600 cursor-default">
                            GitHub link coming soon
                        </span>
                    )}
                </div>
            </div>
        </div>
    );
};

/* ── Project card ── */
const ProjectCard = ({ project, index, inView, onClick }) => (
    <div
        onClick={onClick}
        className={`reveal ${inView ? 'visible' : ''} group relative rounded-2xl overflow-hidden cursor-pointer
                   transition-all duration-300 hover:-translate-y-1`}
        style={{
            background: 'rgba(255,255,255,0.025)',
            border: '1px solid rgba(255,255,255,0.07)',
            transitionDelay: inView ? `${Math.min(index * 80, 320)}ms` : '0ms',
        }}
        onMouseEnter={(e) => {
            e.currentTarget.style.border = `1px solid ${project.borderColor}`;
            e.currentTarget.style.boxShadow = `0 0 30px 0 ${project.glowColor}`;
        }}
        onMouseLeave={(e) => {
            e.currentTarget.style.border = '1px solid rgba(255,255,255,0.07)';
            e.currentTarget.style.boxShadow = 'none';
        }}
    >
        {/* Top accent line */}
        <div className="h-[2px] w-full bg-gradient-to-r from-pink-500 to-rose-500 opacity-60 group-hover:opacity-100 transition-opacity duration-300" />

        <div className="p-6 flex flex-col gap-4">
            {project.badge && (
                <span className={`self-start text-[10px] font-semibold tracking-widest uppercase px-2.5 py-1 rounded-full bg-white/5 border border-white/10 ${project.labelColor}`}>
                    {project.badge}
                </span>
            )}

            <div>
                <h3 className="text-white font-bold text-lg leading-tight mb-1">{project.title}</h3>
                <p className="text-gray-500 text-xs">{project.subtitle}</p>
            </div>

            <p className="text-gray-400 text-sm leading-relaxed line-clamp-3">{project.description}</p>

            <div className="flex flex-wrap gap-1.5 mt-auto pt-2">
                {project.tags.slice(0, 4).map(tag => (
                    <span key={tag} className="text-[11px] px-2.5 py-1 rounded-full bg-white/[0.04] border border-white/[0.08] text-gray-500">
                        {tag}
                    </span>
                ))}
                {project.tags.length > 4 && (
                    <span className="text-[11px] px-2.5 py-1 rounded-full bg-white/[0.04] border border-white/[0.08] text-gray-600">
                        +{project.tags.length - 4}
                    </span>
                )}
            </div>

            <p className={`text-xs font-medium ${project.labelColor} opacity-0 group-hover:opacity-100 transition-opacity duration-200`}>
                Click to expand
            </p>
        </div>
    </div>
);

/* ── Main ── */
const Projects = () => {
    const [headingRef, headingInView] = useInView();
    const [gridRef,    gridInView]    = useInView(0.05);
    const [selected,   setSelected]   = useState(null);

    return (
        <section className="relative bg-black py-24 px-6" id="projects">
            <div className="max-w-5xl mx-auto">
                <div className={`reveal ${headingInView ? 'visible' : ''} flex items-center gap-3 mb-6`}>
                    <span className="h-px w-10 bg-pink-500/60" />
                    <span className="text-xs font-semibold tracking-[0.25em] uppercase text-pink-400/80">What I've Built</span>
                </div>
                <h2
                    ref={headingRef}
                    data-text="PROJECTS"
                    className={`reveal ${headingInView ? 'visible' : ''} glitch-heading text-5xl md:text-7xl lg:text-8xl font-extrabold tracking-tighter mb-16 primary-color`}
                >
                    PROJECTS
                </h2>

                <div
                    ref={gridRef}
                    className="grid grid-cols-1 sm:grid-cols-2 gap-5"
                >
                    {projectData.map((project, index) => (
                        <ProjectCard
                            key={project.title}
                            project={project}
                            index={index}
                            inView={gridInView}
                            onClick={() => setSelected(project)}
                        />
                    ))}
                </div>
            </div>

            <ProjectModal project={selected} onClose={() => setSelected(null)} />
        </section>
    );
};

export default Projects;
